# Generated by Django 5.2.8 on 2025-12-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_is_read_requisition_icon_requisition_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_receive_orders', 'Pode receber e gerenciar pedidos')]},
        ),
    ]
