# Generated by Django 5.2.9 on 2025-12-12 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='requisition_icon'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='requisition_image'),
        ),
    ]
