# Generated by Django 5.2.9 on 2025-12-12 20:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_image_alter_requisition_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image'),
        ),
    ]
