# Generated by Django 5.2.9 on 2025-12-12 21:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_requisition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='requisition_image'),
        ),
    ]
