# Generated by Django 5.2.9 on 2026-01-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_requisition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=10),
        ),
    ]
