# Generated by Django 5.2.9 on 2026-01-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_concluded_at_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.requisition'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
